package dev.ntmr.nucleartech.datagen

import dev.ntmr.nucleartech.content.NTechBlocks
import dev.ntmr.nucleartech.content.NTechItems
import dev.ntmr.nucleartech.datagen.loot.BlockLoots
import dev.ntmr.nucleartech.datagen.provider.NuclearBlockStateProvider
import dev.ntmr.nucleartech.extensions.appendToPath
import net.minecraft.tags.BlockTags
import net.minecraft.tags.TagKey
import net.minecraft.world.item.Items
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.Blocks
import net.minecraftforge.common.Tags
import net.minecraftforge.registries.RegistryObject

object CommonBlocks {
    val data = buildList<BlockDataDefinition<Block>> { with(NTechBlocks) {
        val typePickaxe = setOf(BlockTags.MINEABLE_WITH_PICKAXE)
        val typeShovel = setOf(BlockTags.MINEABLE_WITH_SHOVEL)
        val typeAxe = setOf(BlockTags.MINEABLE_WITH_AXE)

        val levelWood = Tags.Blocks.NEEDS_WOOD_TOOL
        val levelStone = BlockTags.NEEDS_STONE_TOOL
        val levelIron = BlockTags.NEEDS_IRON_TOOL
        val levelDiamond = BlockTags.NEEDS_DIAMOND_TOOL
        val levelNetherite = Tags.Blocks.NEEDS_NETHERITE_TOOL

        addBlock(uraniumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawUranium.get()) })
        addBlock(scorchedUraniumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawUranium.get()) })
        addBlock(thoriumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawThorium.get()) })
        addBlock(titaniumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawTitanium.get()) })
        addBlock(sulfurOre, typePickaxe, levelStone, loot = { addOreDrop(it, NTechItems.sulfur.get(), 2F, 4F) })
        addBlock(niterOre, typePickaxe, levelStone, loot = { addOreDrop(it, NTechItems.niter.get(), 2F, 4F) })
        addBlock(tungstenOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawTungsten.get()) })
        addBlock(aluminiumOre, typePickaxe, levelStone, loot = { addOreDrop(it, NTechItems.rawAluminium.get()) })
        addBlock(fluoriteOre, typePickaxe, levelStone, loot = { addOreDrop(it, NTechItems.fluorite.get(), 2F, 4F) })
        addBlock(berylliumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawBeryllium.get()) })
        addBlock(leadOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawLead.get()) })
        addBlock(oilDeposit, typePickaxe, levelStone)
        addBlock(emptyOilDeposit, typePickaxe, levelStone)
        addBlock(oilSand, typeShovel, levelStone)
        addBlock(ligniteOre, typePickaxe, levelWood, loot = { addOreDrop(it, NTechItems.lignite.get()) })
        addBlock(asbestosOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.asbestosSheet.get()) })
        addBlock(schrabidiumOre, typePickaxe, levelNetherite, loot = { addOreDrop(it, NTechItems.rawSchrabidium.get()) })
        addBlock(australianOre, typePickaxe, levelDiamond, loot = { addOreDrop(it, NTechItems.rawAustralium.get()) })
        addBlock(weidite, typePickaxe, levelDiamond)
        addBlock(reiite, typePickaxe, levelDiamond)
        addBlock(brightblendeOre, typePickaxe, levelDiamond)
        addBlock(dellite, typePickaxe, levelDiamond)
        addBlock(dollarGreenMineral, typePickaxe, levelDiamond)
        addBlock(rareEarthOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawRareEarth.get()) })
        addBlock(cobaltOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawCobalt.get()) })
        addBlock(deepslateUraniumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawUranium.get()) })
        addBlock(scorchedDeepslateUraniumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawUranium.get()) })
        addBlock(deepslateThoriumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawThorium.get()) })
        addBlock(deepslateTitaniumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawTitanium.get()) })
        addBlock(deepslateSulfurOre, typePickaxe, levelStone, loot = { addOreDrop(it, NTechItems.sulfur.get(), 2F, 4F) })
        addBlock(deepslateNiterOre, typePickaxe, levelStone, loot = { addOreDrop(it, NTechItems.niter.get(),  2F, 4F) })
        addBlock(deepslateTungstenOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawTungsten.get()) })
        addBlock(deepslateAluminiumOre, typePickaxe, levelStone, loot = { addOreDrop(it, NTechItems.rawAluminium.get()) })
        addBlock(deepslateFluoriteOre, typePickaxe, levelStone, loot = { addOreDrop(it, NTechItems.fluorite.get(), 2F, 4F) })
        addBlock(deepslateBerylliumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawBeryllium.get()) })
        addBlock(deepslateLeadOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawLead.get()) })
        addBlock(deepslateOilDeposit, typePickaxe, levelStone)
        addBlock(emptyDeepslateOilDeposit, typePickaxe, levelStone)
        addBlock(deepslateAsbestosOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.asbestosSheet.get()) })
        addBlock(deepslateSchrabidiumOre, typePickaxe, levelNetherite, loot = { addOreDrop(it, NTechItems.rawSchrabidium.get()) })
        addBlock(deepslateAustralianOre, typePickaxe, levelDiamond, loot = { addOreDrop(it, NTechItems.rawAustralium.get()) })
        addBlock(deepslateRareEarthOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawRareEarth.get()) })
        addBlock(deepslateCobaltOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawCobalt.get()) })
        addBlock(netherUraniumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawUranium.get()) })
        addBlock(scorchedNetherUraniumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawUranium.get()) })
        addBlock(netherPlutoniumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawPlutonium.get()) })
        addBlock(netherTungstenOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawTungsten.get()) })
        addBlock(netherSulfurOre, typePickaxe, levelStone, loot = { addOreDrop(it, NTechItems.sulfur.get(), 2F,  4F) })
        addBlock(netherPhosphorusOre, typePickaxe, levelStone, loot = { addOreWeightedTable(it, NTechItems.redPhosphorus.get() to .9F, NTechItems.whitePhosphorusIngot.get() to .1F) })
        addBlock(netherSchrabidiumOre, typePickaxe, levelNetherite, loot = { addOreDrop(it, NTechItems.rawSchrabidium.get()) })
        addBlock(meteorUraniumOre, typePickaxe, levelIron)
        addBlock(meteorThoriumOre, typePickaxe, levelIron)
        addBlock(meteorTitaniumOre, typePickaxe, levelIron)
        addBlock(meteorSulfurOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.sulfur.get(), 6F, 12F) })
        addBlock(meteorCopperOre, typePickaxe, levelIron)
        addBlock(meteorTungstenOre, typePickaxe, levelIron)
        addBlock(meteorAluminiumOre, typePickaxe, levelIron)
        addBlock(meteorLeadOre, typePickaxe, levelIron)
        addBlock(meteorLithiumOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawLithium.get()) })
        addBlock(starmetalOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawStarmetal.get()) })
        addBlock(trixite, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.rawTrixite.get()) })
        addBlock(basaltSulfurOre, typePickaxe, levelStone, loot = { addOreDrop(it, NTechItems.sulfur.get(), 2F, 4F) }, model = NuclearBlockStateProvider::axisBlock)
        addBlock(basaltFluoriteOre, typePickaxe, levelStone, loot = { addOreDrop(it, NTechItems.fluorite.get(), 2F, 4F) }, model = NuclearBlockStateProvider::axisBlock)
        addBlock(basaltAsbestosOre, typePickaxe, levelStone, loot = { addOreDrop(it, NTechItems.asbestosSheet.get()) }, model = NuclearBlockStateProvider::axisBlock)
        addBlock(basaltVolcanicGemOre, typePickaxe, levelIron, loot = { addOreDrop(it, NTechItems.volcanicGem.get()) }, model = NuclearBlockStateProvider::axisBlock)

        addBlock(uraniumBlock, typePickaxe, levelStone)
        addBlock(u233Block, typePickaxe, levelStone)
        addBlock(u235Block, typePickaxe, levelStone)
        addBlock(u238Block, typePickaxe, levelStone)
        addBlock(uraniumFuelBlock, typePickaxe, levelStone)
        addBlock(neptuniumBlock, typePickaxe, levelStone)
        addBlock(moxFuelBlock, typePickaxe, levelStone)
        addBlock(plutoniumBlock, typePickaxe, levelStone)
        addBlock(pu238Block, typePickaxe, levelStone)
        addBlock(pu239Block, typePickaxe, levelStone)
        addBlock(pu240Block, typePickaxe, levelStone)
        addBlock(plutoniumFuelBlock, typePickaxe, levelStone)
        addBlock(thoriumBlock, typePickaxe, levelStone)
        addBlock(thoriumFuelBlock, typePickaxe, levelStone)
        addBlock(titaniumBlock, typePickaxe, levelStone)
        addBlock(sulfurBlock, typePickaxe, levelStone)
        addBlock(niterBlock, typePickaxe, levelStone)
        addBlock(redCopperBlock, typePickaxe, levelStone)
        addBlock(advancedAlloyBlock, typePickaxe, levelStone)
        addBlock(tungstenBlock, typePickaxe, levelStone)
        addBlock(aluminiumBlock, typePickaxe, levelStone)
        addBlock(fluoriteBlock, typePickaxe, levelStone)
        addBlock(berylliumBlock, typePickaxe, levelStone)
        addBlock(cobaltBlock, typePickaxe, levelStone)
        addBlock(steelBlock, typePickaxe, levelStone)
        addBlock(leadBlock, typePickaxe, levelStone)
        addBlock(lithiumBlock, typePickaxe, levelStone)
        addBlock(whitePhosphorusBlock, typeShovel, levelWood)
        addBlock(redPhosphorusBlock, typeShovel, levelWood)
        addBlock(yellowcakeBlock, typeShovel, levelStone)
        addBlock(scrapBlock, typeShovel, levelStone)
        addBlock(electricalScrapBlock, typePickaxe, levelStone)
        addBlock(insulatorRoll, typeAxe, levelStone, model = NuclearBlockStateProvider::axisBlock)
        addBlock(fiberglassRoll, typeAxe, levelStone, model = NuclearBlockStateProvider::axisBlock)
        addBlock(asbestosBlock, typePickaxe, levelStone)
        addBlock(trinititeBlock, typePickaxe, levelStone)
        addBlock(nuclearWasteBlock, typePickaxe, levelStone)
        addBlock(schrabidiumBlock, typePickaxe, levelIron)
        addBlock(soliniumBlock, typePickaxe, levelStone)
        addBlock(schrabidiumFuelBlock, typePickaxe, levelIron)
        addBlock(euphemiumBlock, typePickaxe, levelIron)
        addBlock(schrabidiumCluster, typePickaxe, levelIron, model = NuclearBlockStateProvider::columnBlock)
        addBlock(euphemiumEtchedSchrabidiumCluster, typePickaxe, levelIron, model = NuclearBlockStateProvider::columnBlock)
        addBlock(magnetizedTungstenBlock, typePickaxe, levelStone)
        addBlock(combineSteelBlock, typePickaxe, levelStone)
        addBlock(deshReinforcedBlock, typePickaxe, levelStone)
        addBlock(starmetalBlock, typePickaxe, levelStone)
        addBlock(australiumBlock, typePickaxe, levelStone)
        addBlock(weidaniumBlock, typePickaxe, levelStone)
        addBlock(reiiumBlock, typePickaxe, levelStone)
        addBlock(unobtainiumBlock, typePickaxe, levelStone)
        addBlock(daffergonBlock, typePickaxe, levelStone)
        addBlock(verticiumBlock, typePickaxe, levelStone)
        addBlock(titaniumDecoBlock, typePickaxe, levelStone)
        addBlock(redCopperDecoBlock, typePickaxe, levelStone)
        addBlock(tungstenDecoBlock, typePickaxe, levelStone)
        addBlock(aluminiumDecoBlock, typePickaxe, levelStone)
        addBlock(steelDecoBlock, typePickaxe, levelStone)
        addBlock(leadDecoBlock, typePickaxe, levelStone)
        addBlock(berylliumDecoBlock, typePickaxe, levelStone)
        addBlock(asbestosRoof, typePickaxe, levelStone)
        addBlock(hazmatBlock, typeAxe, null)
        addBlock(meteorite, typePickaxe, levelIron)
        addBlock(meteoriteCobblestone, typePickaxe, levelIron, loot = { addSingleDropSilkTouch(it, NTechItems.meteoriteFragment.get()) })
        addBlock(brokenMeteorite, typePickaxe, levelIron, loot = { addSingleDropSilkTouch(it, NTechItems.meteoriteFragment.get()) })
        addBlock(hotMeteoriteCobblestone, typePickaxe, levelIron, loot = BlockLoots::dropWhenSilkTouch)
        addBlock(meteoriteTreasure, typePickaxe, levelIron) // TODO

        addBlock(steelBeam, typePickaxe, levelStone, model = { axisBeam(it, 2F) })
        addBlock(steelScaffold, typePickaxe, levelStone, model = NuclearBlockStateProvider::steelScaffold)
        addBlock(steelGrate, typePickaxe, levelStone, model = NuclearBlockStateProvider::steelGrate, itemModel = { simpleBlockItem(it,  models().getExistingFile(it.registryName!!.appendToPath("4"))) })

        addBlock(glowingMushroom, emptySet(), null, model = NuclearBlockStateProvider::simplePlant, itemModel = NuclearBlockStateProvider::simpleItem)
        addBlock(glowingMushroomBlock, typeAxe, null, loot = { addMushroomBlock(it, glowingMushroom.get()) }, model = NuclearBlockStateProvider::mushroomBlock)
        addBlock(glowingMushroomStem, typeAxe, null, loot = BlockLoots::dropWhenSilkTouch, model =  { mushroomBlock(it, glowingMushroomBlock.get()) })
        addBlock(deadGrass, typeShovel, null, loot = { addSingleDropSilkTouch(it, Blocks.DIRT) }, model = NuclearBlockStateProvider::grassLikeBlock)
        addBlock(glowingMycelium, typeShovel, null, loot = { addSingleDropSilkTouch(it, Blocks.DIRT) }, model = NuclearBlockStateProvider::grassLikeBlock)
        addBlock(trinitite, typeShovel, null, loot = { addSingleDropSilkTouch(it, NTechItems.trinitite.get()) })
        addBlock(redTrinitite, typeShovel, null, loot = { addSingleDropSilkTouch(it, NTechItems.trinitite.get()) })
        addBlock(charredLog, typeAxe, null, loot = { addOreWithRareSideDrop(it, Items.COAL, 2F, 4F, NTechItems.burntBark.get(), 0.001) }, model = NuclearBlockStateProvider::logBlock)
        addBlock(charredPlanks, typeAxe, null, loot = { addOreDrop(it, Items.COAL) })
        addBlock(slakedSellafite, typePickaxe, levelStone)
        addBlock(sellafite, typePickaxe, levelStone)
        addBlock(hotSellafite, typePickaxe, levelStone)
        addBlock(boilingSellafite, typePickaxe, levelStone)
        addBlock(blazingSellafite, typePickaxe, levelStone)
        addBlock(infernalSellafite, typePickaxe, levelStone)
        addBlock(sellafiteCorium, typePickaxe, levelStone)
        addBlock(corium, typePickaxe, levelStone)
        addBlock(corebblestone, typePickaxe, levelStone)
        addBlock(siren, typePickaxe, levelStone, model = NuclearBlockStateProvider::columnBlock)
        addBlock(safe, typePickaxe, levelStone, model = NuclearBlockStateProvider::orientableBlockWithFront)
        addBlock(ironAnvil, typePickaxe, levelStone, model = NuclearBlockStateProvider::anvil)
        addBlock(leadAnvil, typePickaxe, levelStone, model = NuclearBlockStateProvider::anvil)
        addBlock(steelAnvil, typePickaxe, levelStone, model = NuclearBlockStateProvider::anvil)
        addBlock(meteoriteAnvil, typePickaxe, levelIron, model = NuclearBlockStateProvider::anvil)
        addBlock(starmetalAnvil, typePickaxe, levelIron, model = NuclearBlockStateProvider::anvil)
        addBlock(ferrouraniumAnvil, typePickaxe, levelIron, model = NuclearBlockStateProvider::anvil)
        addBlock(bismuthAnvil, typePickaxe, levelIron, model = NuclearBlockStateProvider::anvil)
        addBlock(schrabidateAnvil, typePickaxe, levelIron, model = NuclearBlockStateProvider::anvil)
        addBlock(dineutroniumAnvil, typePickaxe, levelDiamond, model = NuclearBlockStateProvider::anvil)
        addBlock(murkyAnvil, typePickaxe, null, model = NuclearBlockStateProvider::anvil)
        addBlock(coatedCable, typePickaxe, levelWood)
        addBlock(coatedUniversalFluidDuct, typePickaxe, levelWood, model = NuclearBlockStateProvider::simpleTintedBlock)
        addBlock(steamPressBase, typePickaxe, levelStone, model = NuclearBlockStateProvider::simpleExistingModelBlock, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(steamPressFrame, typePickaxe, levelStone, loot = BlockLoots::noDrop, model = NuclearBlockStateProvider::simpleExistingModelBlock, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(steamPressTop, typePickaxe, levelStone, loot = BlockLoots::noDrop, model = NuclearBlockStateProvider::simpleExistingModelBlock, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(blastFurnace, typePickaxe, levelStone, model = { litHorizontalBlock(it, top = extend(blockTexture(it), "_top"), topLit = extend(blockTexture(it), "_top_on")) })
        addBlock(combustionGenerator, typePickaxe, levelStone, model = NuclearBlockStateProvider::litHorizontalBlock)
        addBlock(electricFurnace, typePickaxe, levelStone, model = { litHorizontalBlock(it, bottom = extend(blockTexture(it), "_bottom"), top = extend(blockTexture(it), "_top")) })
        addBlock(shredder, typePickaxe, levelStone, model = { cubeAllSides(it, north = extend(blockTexture(it), "_front"), south = extend(blockTexture(it), "_front"), east = extend(blockTexture(it), "_side"), west = extend(blockTexture(it), "_side")) })
        addBlock(assembler, typePickaxe, levelStone, model = NuclearBlockStateProvider::specialModelParticles, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(chemPlant, typePickaxe, levelStone, model = NuclearBlockStateProvider::specialModelParticles, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(turbine, typePickaxe, levelStone, model = NuclearBlockStateProvider::columnBlock)
        addBlock(smallCoolingTower, typePickaxe, levelStone, model = NuclearBlockStateProvider::specialModelParticles, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(largeCoolingTower, typePickaxe, levelStone, model = NuclearBlockStateProvider::specialModelParticles, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(oilDerrick, typePickaxe, levelStone, model = NuclearBlockStateProvider::specialModelParticles, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(pumpjack, typePickaxe, levelStone, model = NuclearBlockStateProvider::specialModelParticles, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(centrifuge, typePickaxe, levelStone, model = NuclearBlockStateProvider::specialModelParticles, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkColumn, typePickaxe, levelStone, loot = BlockLoots::noDrop, model = NuclearBlockStateProvider::emptyModelBlock, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkRod, typePickaxe, levelStone, loot = BlockLoots::rbmkDrops, model = { specialModelParticles(it, "other/rbmk/rods") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkModeratedRod, typePickaxe, levelStone, loot = BlockLoots::rbmkDrops, model = { specialModelParticles(it, "other/rbmk/moderated_rods") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkReaSimRod, typePickaxe, levelStone, loot = BlockLoots::rbmkDrops, model = { specialModelParticles(it, "other/rbmk/reasim_rods") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkModeratedReaSimRod, typePickaxe, levelStone, loot = BlockLoots::rbmkDrops, model = { specialModelParticles(it, "other/rbmk/moderated_reasim_rods") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkReflector, typePickaxe, levelStone, loot = BlockLoots::rbmkDrops, model = { specialModelParticles(it, "other/rbmk/reflector") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkModerator, typePickaxe, levelStone, loot = BlockLoots::rbmkDrops, model = { specialModelParticles(it, "other/rbmk/moderator") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkAbsorber, typePickaxe, levelStone, loot = BlockLoots::rbmkDrops, model = { specialModelParticles(it, "other/rbmk/absorber") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkBoilerColumn, typePickaxe, levelStone, loot = BlockLoots::noDrop, model = NuclearBlockStateProvider::emptyModelBlock, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkBoiler, typePickaxe, levelStone, loot = BlockLoots::rbmkDrops, model = { specialModelParticles(it, "other/rbmk/boiler") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkBlank, typePickaxe, levelStone, loot = BlockLoots::rbmkDrops, model = { specialModelParticles(it, "other/rbmk/blank") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkManualControlRod, typePickaxe, levelStone, loot = BlockLoots::rbmkDrops, model = { specialModelParticles(it, "other/rbmk/manual_control") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkModeratedControlRod, typePickaxe, levelStone, loot = BlockLoots::rbmkDrops, model = { specialModelParticles(it, "other/rbmk/moderated_control") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkAutoControlRod, typePickaxe, levelStone, loot = BlockLoots::rbmkDrops, model = { specialModelParticles(it, "other/rbmk/auto_control") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(rbmkSteamConnector, typePickaxe, levelStone)
        addBlock(rbmkInlet, typePickaxe, levelStone)
        addBlock(rbmkOutlet, typePickaxe, levelStone)
        addBlock(rbmkConsole, typePickaxe, levelStone, model = { specialModelParticles(it, "other/rbmk/console_particles") })
        addBlock(rbmkDebris, typePickaxe, levelStone, model = { simpleObjModelBlock(it, modLoc("models/other/rbmk/debris.obj"), modLoc("other/rbmk/debris")) })
        addBlock(rbmkBurningDebris, typePickaxe, levelStone, model = { simpleObjModelBlock(it, modLoc("models/other/rbmk/debris.obj"), modLoc("other/rbmk/burning_debris")) })
        addBlock(rbmkRadioactiveDebris, typePickaxe, levelStone, model = { simpleObjModelBlock(it, modLoc("models/other/rbmk/debris.obj"), modLoc("other/rbmk/radioactive_debris")) })
        addBlock(littleBoy, typePickaxe, levelStone, model = { specialModelParticles(it, "other/little_boy/little_boy_particles") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(fatMan, typePickaxe, levelStone, model = { specialModelParticles(it, "other/fat_man/fat_man_particles") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(volcanoCore, typePickaxe, levelStone)
        addBlock(launchPad, typePickaxe, levelStone, model = { specialModelParticles(it, "other/launch_pad/launch_pad_particles") }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(launchPadPart, typePickaxe, levelStone, loot = BlockLoots::noDrop, model = { copiedBlock(it, launchPad.get()) }, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(genericMultiBlockPart, typePickaxe, levelStone, loot = BlockLoots::noDrop, model = NuclearBlockStateProvider::emptyModelBlock, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(genericMultiBlockPort, typePickaxe, levelStone, loot = BlockLoots::noDrop, model = NuclearBlockStateProvider::emptyModelBlock, itemModel = NuclearBlockStateProvider::noItemModel)
        addBlock(oilPipe, typePickaxe, levelStone, loot = BlockLoots::noDrop, itemModel = NuclearBlockStateProvider::noItemModel)

        addBlock(decoRbmkBlock, typePickaxe, levelStone)
        addBlock(decoRbmkSmoothBlock, typePickaxe, levelStone)
    }}

    private fun <T : Block> MutableList<BlockDataDefinition<Block>>.addBlock(
        block: RegistryObject<out T>,
        toolTypes: Set<TagKey<Block>>,
        toolLevel: TagKey<Block>?,
        loot: BlockLoots.(block: T) -> Unit = BlockLoots::dropSelf,
        model: NuclearBlockStateProvider.(block: T) -> Unit = NuclearBlockStateProvider::simpleBlock,
        itemModel: NuclearBlockStateProvider.(block: T) -> Unit = NuclearBlockStateProvider::copiedBlockItem
    ) {
        // UNSAFE! Functions contained in the BlockDataDefinition instance *must* be passed the result of block.get(), otherwise things might crash!
        @Suppress("UNCHECKED_CAST")
        add(BlockDataDefinition(block, toolTypes, toolLevel, loot, model, itemModel) as BlockDataDefinition<Block>)
    }

    data class BlockDataDefinition<T : Block>(
        val block: RegistryObject<out T>,
        val toolTypes: Set<TagKey<Block>>,
        val toolLevel: TagKey<Block>?,
        val loot: BlockLoots.(block: T) -> Unit = BlockLoots::dropSelf,
        val model: NuclearBlockStateProvider.(block: T) -> Unit = NuclearBlockStateProvider::simpleBlock,
        val itemModel: NuclearBlockStateProvider.(block: T) -> Unit = NuclearBlockStateProvider::copiedBlockItem
    )
}
